# ekf.yaml
# robot_localization paketi için EKF konfigürasyonu
# RF2O Lazer Odometri + ZED 2i Görsel-Ataletsel Odometri (VIO) füzyonu

ekf_filter_node:
  ros__parameters:
    # Genel Ayarlar
    frequency: 30.0                  # Filtrenin çalışma frekansı (Hz)
    sensor_timeout: 0.1              # Sensör verisi gelmezse ne kadar bekleneceği (saniye)
    two_d_mode: false                # ZED 3D veri sağladığı için 2D modunu kapatıyoruz
    publish_tf: true                 # EKF'nin odom -> base_link transformasyonunu yayınlamasını istiyoruz
    
    # Koordinat Çerçeveleri (Frame)
    map_frame: map                   # Sabit, global çerçeve (şimdilik kullanmayacağız)
    odom_frame: odom                 # Odometrinin başlangıç noktası, EKF tarafından yönetilecek
    base_link_frame: base_link       # Robotun ana çerçevesi
    world_frame: odom                # EKF'nin yayınlayacağı ana çerçeve odom olacak

    # --- SENSÖR GİRDİLERİ ---

    # ODOMETRI 0: RF2O Lazer Odometri
    odom0: /odom_rf2o
    odom0_config: [true,  true,  false,   # [X, Y, Z] pozisyonları
                   false, false, true,    # [Roll, Pitch, Yaw] açıları
                   true,  true,  false,   # [Vx, Vy, Vz] lineer hızlar
                   false, false, true]    # [Vroll, Vpitch, Vyaw] açısal hızlar
    odom0_differential: false
    odom0_relative: false

    # ODOMETRI 1: ZED 2i Görsel-Ataletsel Odometri (VIO)
    odom1: /zed2i/zed_node/odom
    odom1_config: [true,  true,  true,    # [X, Y, Z] pozisyonları
                   true,  true,  true,    # [Roll, Pitch, Yaw] açıları
                   true,  true,  true,    # [Vx, Vy, Vz] lineer hızlar
                   true,  true,  true]    # [Vroll, Vpitch, Vyaw] açısal hızlar
    odom1_differential: false
    odom1_relative: false

    # IMU 0: ZED 2i IMU Verisi (isteğe bağlı ama önerilir)
    # Eğer ZED'in ham IMU verisini de eklemek isterseniz bu bölümü açabilirsiniz
    # imu0: /zed2i/zed_node/imu/data
    # imu0_config: [false, false, false,
    #               true,  true,  true,
    #               false, false, false,
    #               true,  true,  true,
    #               true,  true,  true]
    # imu0_differential: false

    # Gürültü Parametreleri (İsteğe bağlı - varsayılan değerler kullanılabilir)
    # Bu parametreler sensörlerin güvenilirliğini belirler
    # odom0_nodelay: 0.0
    # odom1_nodelay: 0.0
